// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: employe.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Zip           int32                  `protobuf:"varint,2,opt,name=zip,proto3" json:"zip,omitempty"` // Use int32 or int64 to specify exact size in proto
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_employe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_employe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_employe_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetZip() int32 {
	if x != nil {
		return x.Zip
	}
	return 0
}

type Employee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IsActive      bool                   `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Balance       float64                `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Address       *Address               `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Scores        []int64                `protobuf:"varint,6,rep,packed,name=scores,proto3" json:"scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Employee) Reset() {
	*x = Employee{}
	mi := &file_employe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Employee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employee) ProtoMessage() {}

func (x *Employee) ProtoReflect() protoreflect.Message {
	mi := &file_employe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employee.ProtoReflect.Descriptor instead.
func (*Employee) Descriptor() ([]byte, []int) {
	return file_employe_proto_rawDescGZIP(), []int{1}
}

func (x *Employee) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Employee) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Employee) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Employee) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Employee) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Employee) GetScores() []int64 {
	if x != nil {
		return x.Scores
	}
	return nil
}

// Wrapper for list of employees (used for benchmarking)
type Employees struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Employee            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Employees) Reset() {
	*x = Employees{}
	mi := &file_employe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Employees) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employees) ProtoMessage() {}

func (x *Employees) ProtoReflect() protoreflect.Message {
	mi := &file_employe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employees.ProtoReflect.Descriptor instead.
func (*Employees) Descriptor() ([]byte, []int) {
	return file_employe_proto_rawDescGZIP(), []int{2}
}

func (x *Employees) GetList() []*Employee {
	if x != nil {
		return x.List
	}
	return nil
}

var File_employe_proto protoreflect.FileDescriptor

const file_employe_proto_rawDesc = "" +
	"\n" +
	"\remploye.proto\x12\bemployee\"/\n" +
	"\aAddress\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x10\n" +
	"\x03zip\x18\x02 \x01(\x05R\x03zip\"\xaa\x01\n" +
	"\bEmployee\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tis_active\x18\x02 \x01(\bR\bisActive\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x01R\abalance\x12+\n" +
	"\aaddress\x18\x04 \x01(\v2\x11.employee.AddressR\aaddress\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x16\n" +
	"\x06scores\x18\x06 \x03(\x03R\x06scores\"3\n" +
	"\tEmployees\x12&\n" +
	"\x04list\x18\x01 \x03(\v2\x12.employee.EmployeeR\x04listB\"Z github.com/GenshIv/silentjson/pbb\x06proto3"

var (
	file_employe_proto_rawDescOnce sync.Once
	file_employe_proto_rawDescData []byte
)

func file_employe_proto_rawDescGZIP() []byte {
	file_employe_proto_rawDescOnce.Do(func() {
		file_employe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_employe_proto_rawDesc), len(file_employe_proto_rawDesc)))
	})
	return file_employe_proto_rawDescData
}

var file_employe_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_employe_proto_goTypes = []any{
	(*Address)(nil),   // 0: employee.Address
	(*Employee)(nil),  // 1: employee.Employee
	(*Employees)(nil), // 2: employee.Employees
}
var file_employe_proto_depIdxs = []int32{
	0, // 0: employee.Employee.address:type_name -> employee.Address
	1, // 1: employee.Employees.list:type_name -> employee.Employee
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_employe_proto_init() }
func file_employe_proto_init() {
	if File_employe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_employe_proto_rawDesc), len(file_employe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_employe_proto_goTypes,
		DependencyIndexes: file_employe_proto_depIdxs,
		MessageInfos:      file_employe_proto_msgTypes,
	}.Build()
	File_employe_proto = out.File
	file_employe_proto_goTypes = nil
	file_employe_proto_depIdxs = nil
}
